USE prep_expert_dev_cms;

CREATE TABLE courses (
    course_id INT NOT NULL PRIMARY KEY,
    location_type VARCHAR(255),
    test_type VARCHAR(255),
    class_type VARCHAR(255),
    finalized_instructor VARCHAR(255),
    course_start_date DATE,
    end_date DATE,
    meeting_days VARCHAR(255),
    created_by VARCHAR(255),
    days_total_number INT,
    lesson_length INT,
    lessons_per_class_day INT,
    breaks_for_lunch BIT NOT NULL DEFAULT 0,
    lesson_start_time INT,
    lesson_end_time INT,
    is_schedule_created BIT NOT NULL DEFAULT 0,
    schedule_created_by VARCHAR(255),
    schedule_created_date DATE,
    is_schedule_published BIT NOT NULL DEFAULT 0,
    schedule_published_date DATE,
    is_schedule_audited BIT NOT NULL DEFAULT 0,
    is_schedule_removed BIT NOT NULL DEFAULT 0,
    schedule_remove_date DATE,
    first_choice_instructor  VARCHAR(255),
    is_offered_to_first_choice BIT NOT NULL DEFAULT 0,
    date_offered_to_first_choice DATE,
    is_accepted_by_instructor BIT NOT NULL DEFAULT 0,
    other_instructor_offered  VARCHAR(255),
    other_instructor_offered_date DATE,
    instructor_notes  VARCHAR(255),
    is_60_day_checkin_complete BIT NOT NULL DEFAULT 0,
    60_day_checkin_date DATE,
    is_two_week_offer_complete BIT NOT NULL DEFAULT 0,
    two_week_offer_official_date DATE,
    is_instructor_agreement_completed BIT NOT NULL DEFAULT 0,
    is_pre_course_conversation_complete BIT NOT NULL DEFAULT 0,
    pre_course_conversation_done_by VARCHAR(255),
    pre_course_conversation_date VARCHAR(255),
    enrollment INT,
    is_TA_needed BIT NOT NULL DEFAULT 0,
    number_of_TAs_needed INT,
    is_offered_to_TA BIT NOT NULL DEFAULT 0,
    TA_offer_date DATE,
    TA_offer_names VARCHAR(255),
    is_accepted_by_TA BIT NOT NULL DEFAULT 0,
    TA1_name VARCHAR(255),
    TA1_accepted_date DATE,
    is_TA1_agreement_complete BIT NOT NULL DEFAULT 0,
    TA1_agreement_date DATE,
    TA2_name VARCHAR(255),
    TA2_accepted_date DATE,
    is_TA2_agreement_complete BIT NOT NULL DEFAULT 0,
    TA2_agreement_date DATE,
    TA3_name VARCHAR(255),
    TA3_accepted_date DATE,
    is_TA3_agreement_complete BIT NOT NULL DEFAULT 0,
    TA3_agreement_date DATE,
    TA4_name VARCHAR(255),
    TA4_accepted_date DATE,
    is_TA4_agreement_complete BIT NOT NULL DEFAULT 0,
    TA4_agreement_date DATE,
    is_template_used BIT NOT NULL DEFAULT 0,
    classroom_created_by VARCHAR(255),
    classroom_created_date DATE,
    in_person_city_id INT,
    is_facility_reserved BIT NOT NULL DEFAULT 0,
    facility_reserve_date DATE
);