INSERT INTO courses (
    course_id,
    location_type,
    test_type,
    class_type,
    finalized_instructor,
    course_start_date,
    end_date,
    meeting_days,
    created_by,
    days_total_number,
    lesson_length,
    lessons_per_class_day,
    breaks_for_lunch,
    lesson_start_time,
    lesson_end_time,
    is_schedule_created,
    schedule_created_by,
    schedule_created_date,
    is_schedule_published,
    schedule_published_date,
    is_schedule_audited,
    is_schedule_removed,
    schedule_remove_date,
    first_choice_instructor ,
    is_offered_to_first_choice,
    is_accepted_by_instructor,
    other_instructor_offered ,
    other_instructor_offered_date,
    instructor_notes ,
    is_60_day_checkin_complete,
    60_day_checkin_date,
    is_two_week_offer_complete,
    two_week_offer_official_date,
    is_instructor_agreement_completed,
    is_pre_course_conversation_complete,
    pre_course_conversation_done_by,
    pre_course_conversation_date,
    enrollment,
    is_TA_needed,
    number_of_TAs_needed,
    is_offered_to_TA,
    TA_offer_date,
    TA_offer_names,
    is_accepted_by_TA,
    TA1_name,
    TA1_accepted_date,
    is_TA1_agreement_complete,
    TA1_agreement_date,
    TA2_name,
    TA2_accepted_date,
    is_TA2_agreement_complete,
    TA2_agreement_date,
    TA3_name,
    TA3_accepted_date,
    is_TA3_agreement_complete,
    TA3_agreement_date,
    TA4_name,
    TA4_accepted_date,
    is_TA4_agreement_complete,
    TA4_agreement_date,
    is_template_used,
    classroom_created_by,
    classroom_created_date,
    in_person_city_id,
    is_facility_reserved,
    facility_reserve_date
) VALUES (
    1,
    'online',
    'SAT',
    '6-Week',
    'Clay Cooper',
    '2018-12-25',
    '2018-12-25',
    'MW',
    'Ben Smith',
    18,
    3,
    1,
    0,
    3,
    6,
    1,
    'Ben Smith',
    '2018-12-25',
    1,
    '2018-12-25',
    1,
    0,
    '2018-12-25',
    'Clay Cooper' ,
    1,
    1,
    'Ben Smith' ,
    '2018-12-25',
    'Main instructor sucks',
    1,
    '2018-12-25',
    1,
    '2018-12-25',
    1,
    1,
    'Ben Smith',
    '2018-12-25',
    100,
    1,
    2,
    1,
    '2018-12-25',
    'Miguel, Samson, Moses',
    1,
    'Miguel',
    '2018-12-25',
    1,
    '2018-12-25',
    'Samson',
    '2018-12-25',
    1,
    '2018-12-25',
    'Moses',
    '2018-12-25',
    1,
    '2018-12-25',
    'Jesus',
    '2018-12-25',
    1,
    '2018-12-25',
    1,
    'Ben Smith',
    '2018-12-25',
    10000,
    1,
    '2018-12-25'
);